services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-tweteer-img
    container_name: container-tweteer-server
    command: /app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-tweteer-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-tweteer-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-tweeter-client
    stdin_open: true
    container_name: myapp-tweeter-client-container
    command: yarn start
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-tweteer-network

networks:
    app-tweteer-network:
        driver: bridge
volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local